version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-llm-bot
    env_file:
      - .env
    restart: unless-stopped
    
    # Настройки логирования
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    
    # Healthcheck для мониторинга
    healthcheck:
      test: ["CMD", "python", "-c", "import config; config.get_telegram_token()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Политики перезапуска
    stop_grace_period: 30s
    
    # Метки для мониторинга
    labels:
      - "app=telegram-llm-bot"
      - "version=0.1.0"
      - "environment=production"

# Сеть для изоляции
networks:
  default:
    driver: bridge
    name: telegram-bot-network

# Volumes для логов (опционально)
volumes:
  logs:
    driver: local 